---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Home of The Best Puckin' Hockey Podcast"
keywords:    "podcast,hockey,nhl,khl,trade,signing,extension,rumor,fun,funny"
description: "The official place to find out mroe about The Best Puckin' Hockey Podcast"
source_link: "https://github.com/kymahi/kymahi.github.io/"
google_analytics_key: 'G-JW1FJ7DJTW'


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  red-line:  '#ff828e'
  blue-line: '#3191ff'
  dark-gray: '#505050'

kramdown:
  auto_ids:  false

